version: '3.8'

services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        GIT_USER_NAME: ${GIT_USER_NAME:-Claude User}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL:-claude@example.com}
        SYSTEM_PACKAGES: ${SYSTEM_PACKAGES:-}
    container_name: claude-code-docker
    environment:
      - NODE_ENV=production
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER:-}
      - TWILIO_TO_NUMBER=${TWILIO_TO_NUMBER:-}
      - CONDA_PREFIX=${CONDA_PREFIX:-}
      - CONDA_EXTRA_DIRS=${CONDA_EXTRA_DIRS:-}
    volumes:
      # Mount workspace directory
      - ./workspace:/workspace
      # Mount Claude home for persistent auth
      - claude-home:/home/claude-user/.claude
      # Mount SSH keys if needed
      - ./ssh:/home/claude-user/.ssh:ro
      # Mount scripts directory
      - ./scripts:/home/claude-user/scripts
    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - claude-network

volumes:
  claude-home:
    driver: local

networks:
  claude-network:
    driver: bridge